### ISSUE TITLE
Erro ServiceProvider and PHPExcel_Shared_Font

### ISSUE THREAD

**Issue by Hatalias** [vdomah/octoexcel#1]
Good afternoon, I tried several alternatives, but I can not install Maatwebsite\Excel in October.
I need a help.

**Comment by vdomah** [comment]
Hi! Plugin is currently in review process and I hope will soon be on October Market. So it will be much easier for you to install it.

Can you post full error message here?

**Comment by Hatalias** [comment]
Good afternoon.
This error first appears.
![erro01](https://cloud.githubusercontent.com/assets/5147951/20896553/85966f94-bb05-11e6-958e-8ea1c64e7780.png)

When I put the Maatwebsite files in the plugin folder it shows this error
![erro02](https://cloud.githubusercontent.com/assets/5147951/20896560/8f3edacc-bb05-11e6-801a-7f3d7f8e0ca4.png)

**Comment by Hatalias** [comment]
I had problems with these classes
Class 'PHPExcel_Settings' not found
Class 'PHPExcel_Shared_Font' not found

**Comment by vdomah** [comment]
Why do you put Maatwebsite files anywhere? You need to put whole octoexcel plugin in /plugins/vdomah/excel folder.
And then relogin to admin panel
