### ISSUE TITLE
export file type

### ISSUE THREAD

**Issue by bkrajendra** [vdomah/octoexcel#12]
can we just add more file type to following array to get it working?

```
    public static function export($class, $filename, $type = 'csv')
    {
        if (! in_array($type, ['xls', 'csv'])) {
            $type = 'csv';
        }

        $fn = $filename;

        return self::excel()->download(new $class, $fn.'.'.$type);
    }

```

why its only limited to `['xls', 'csv']`
can we just allow whats passed as an argument from `export `method?

I guess it does support many [types](https://docs.laravel-excel.com/3.1/exports/export-formats.html)

**Comment by vdomah** [comment]
yes, you're right. Will do that
