### ISSUE TITLE
Compatibility with PhpOffice\PhpSpreadsheet\Reader\IReader

### ISSUE THREAD

**Issue by artmin** [vdomah/octoexcel#18]
**Problem descriptions**

When making a standard export, exceptions are thrown because of incompatibility of Vdomah\Excel\Classes\XlsxStyled class with PhpOffice\PhpSpreadsheet\Reader\IReader class (as present in Maatwebsite\Excel in version 3.1)

**Solution**

Adjust method declaration according to inherited class:
Line 76:
`public function canRead(string $pFilename) : bool`
Line 325:
`public function load(string $pFilename, int $flags = 0)`

**Comment by vdomah** [comment]
Thanks for reporting! Fixed in latest version
