### ISSUE TITLE
Recently it stopped working on all of my sites

### ISSUE THREAD

**Issue by bkrajendra** [vdomah/octoexcel#3]
Recently it stopped working on all of my sites. Its throwing error

```
Call to undefined method Vdomah\Excel\Classes\Excel::create()
```
I'm using it as:

```
function onStart()
{
    use Vdomah\Excel\Classes\Excel; //earlier was working without this
    $users =  RainLab\User\Models\User::all();
    $userArray = $users->toArray();

    Excel::create('ISBM-Staff', function($excel) use($userArray){

    $excel->sheet('User-List', function($sheet) use($userArray) {

        $sheet->fromArray($userArray);

    });

	})->download('xls');
}
```

**Comment by vdomah** [comment]
Yes, month ago plugin was rewritten due to issue reported. Now as stated in the README you need to call Excel::excel()->{method} instead of Excel::{method}
https://github.com/vdomah/octoexcel

So it will be Excel::excel()->create in your case

**Comment by bkrajendra** [comment]
Thank you very much. Issue is resolved now!
