### ISSUE TITLE
FatalErrorException: Class Illuminate\View\Factory contains 1 abstract method

### ISSUE THREAD

**Issue by vojtasvoboda** [vdomah/octoexcel#4]
Hi, could you please help me? I have created new plugin and run:

`composer require maatwebsite/excel:~2.1.0`

but I'm getting:

```
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class Illuminate\View\Factory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\View\Factory::replaceNamespace)
```

So I tried:

`composer dump autoload` in root and also in plugin directory, but didn't helps.

There is some magic, that your vendor directory contains Laravel 5.2 libraries and mine vendor contains Laravel 5.4. My PHP version is 5.6.

Do you know, where could be my fail? Thanks a lot

**Comment by vdomah** [comment]
fixed with new version 1.0.3
