### ISSUE TITLE
application crush after plugin install

### ISSUE THREAD

**Issue by dziurawy** [vdomah/octoexcel#5]
When i try to install the plugin,

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Illuminate\Support\Arr::first() must be callable, null given, called in /var/www/ea/plugins/vdomah/excel/vendor/illuminate/support/Collection.php on line 338 and defined in /var/www/ea/vendor/laravel/framework/src/Illuminate/Support/Arr.php:150

edit:
It looks like in this particual server configuration, october is mixing illuminate/support classes from laravel/framework/src and vdomah/excel/vendor

**Comment by vdomah** [comment]
fixed with new version 1.0.3
