### ISSUE TITLE
Export From Template Code Sections

### ISSUE THREAD

**Issue by shakogele** [vdomah/octoexcel#6]
Hello,
When I try to export from CMS templates code section it is not downloading a file, it just returns raw data. What I am doing wrong?
Here is my code:
***
use Vdomah\Excel\Classes\Excel;
use Acme\Test\Models\User;
function onExportExcel(){
    Excel::excel()->create('users', function($excel) {
        $excel->sheet('Sheet', function($sheet) {
            $model = User::get();
            $sheet->fromModel($model);
        });
    })->download('csv');
}
***

**Comment by vdomah** [comment]
Hi, missed this issue, sorry.
It's hard to tell what's the difference. If it works from component php code, you can move this function there.

**Comment by vdomah** [comment]
issue is outdated because of plugin migration to v3 of Laravel-Excel
