### ISSUE TITLE
Need to push a new build

### ISSUE THREAD

**Issue by LukeTowers** [vdomah/octoexcel#9]
@vdomah you need to release a new version bump so that the marketplace server can rebuild your plugin package (including the dependencies) and people can update to the rebuilt plugin as your plugin version currently on the marketplace embeds a version of illuminate/support that is incompatible with the current version of October: https://github.com/octobercms/october/issues/4009

**Comment by Verbat** [comment]
Hi vdomah,

can you by chance release a new version bump as the current does not run under the latest october build.

Thanks

**Comment by vdomah** [comment]
released new version. Please try

**Comment by Verbat** [comment]
It works, thank you very much.

**Comment by vdomah** [comment]
@LukeTowers please enable the plugin on the Marketplace, thanks

**Comment by LukeTowers** [comment]
@vdomah I don't have control over the marketplace, you'll need to send an email to hello@octobercms.com.

**Comment by Verbat** [comment]
Hi @vdomah , can you check again? The plugin is still not available at the marketplace.
